### ISSUE TITLE
adBTC support other captcha methods (Symbols, and hCaptcha)

### ISSUE THREAD

**Issue by sunk818** [Faucet-Collector/scripts#637]
[adBTC ](https://github.com/Faucet-Collector/scripts/blob/e8e507a97049622fca64784a7d5510c9bc126b27/adBTC/adBTC.fc)supports reCaptcha, hCaptcha, and Symbols.

Google's reCaptcha knows FaucetCollector is a bot and it takes many reCaptcha screens to get a pass. Its not uncommon to go through 5-6 screens all done correctly while reCaptcha will say try again or it was incorrect. The experience is easier if done on a desktop Chrome browser.

So, barring adjusting facuetcollector to [behave more like a desktop browser ](https://antoinevastel.com/bot%20detection/2018/01/17/detect-chrome-headless-v2.html), I'd like to **suggest supporting symbols or hCaptcha** as well.

hCaptcha with Chrome Privacy Pass (CloudFlare) can sometimes bypass with just a click. If you have to solve, then they will provide a "credit" of 5 bypasses before having to solve an hCaptcha. Privacy Pass is a Chrome extension. Sometimes works great to help bypass.

**Comment by cgerabit** [comment]
adbtc already support recaptcha and number captcha also hcaptcha is not supported yet by the software
