### ISSUE TITLE
PipeFlair.io - Dash not redeemed

### ISSUE THREAD

**Issue by Zigeraut** [Faucet-Collector/scripts#642]
When dash is available it seems to skip over Dash claiming its not ready when it is

**Comment by sunk818** [comment]
https://github.com/Faucet-Collector/scripts/blob/aba194f648d21d5ddc05c11d4822d90b2f46cc6d/PipeFlare.io/PipeFlare.io.fc

**Comment by Zigeraut** [comment]
Using this script posted, Dash does work but now ZEC does not? Maybe site is changing code?

**Comment by Zigeraut** [comment]
Lets re-iterate... They did a complete site change. so it needs redone please

**Comment by aviramdayan** [comment]
@Zigeraut thanks for your review, i'll check that about 1 hour or less.

**Comment by aviramdayan** [comment]
i get - DNS_PROBE_FINISHED_NXDOMAIN

**Comment by Zigeraut** [comment]
Im in the site now, and refreshed for safety to make sure, looks like faucets were moved to:
https://pipeflare.io/dailyrewards
 - times were removed so you dont know exactly how long you have left to wait
 - Hidden Recaptcha? (I dont see it when claiming but could be hidden)

**Comment by aviramdayan** [comment]
yeah now load, i'll check

**Comment by aviramdayan** [comment]
can you send me message pm in discord?  @AviramDayan#4435

**Comment by Zigeraut** [comment]
@aviramdayan it says Not Found... here is mine: Zigeraut#1469
